import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import Navigation from './Navigation'
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'BlogiFy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link rel="icon"  type="image/x-icon" href="/favicon.ico" />
      </Head>
      
      <body className={inter.className}>
        <Navigation/>
        {children}
        </body>
    </html>
  )
}
